server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - 'youtube'
            - 'company'
          uri: https://github.com/Daulet402/spring-cloud-config-test
